### ISSUE TITLE
Request: support for SMTP and other non-HTTP services

### ISSUE THREAD

**Issue by Taomyn** [ugoviti/zabbix-templates#10]
Would it be possible for the template to also check SSL certificates on other services? For me I need to know the expiration of my SMTP server's certificate, but others could be useful if there are any useful ones.

**Comment by ugoviti** [comment]
Hi Taomyn,

if in the csv file you list your host like:

smtp.yourserver.com:465

doesn't works?

of course you must selectively disable the items for http monitoring for this host, because isn't a http server and the "HTTP response code" items will trigger a PROBLEM

King Regards

**Comment by Taomyn** [comment]
Wow, it does work, I was stupid not to just try it, but I'm using a Powershell script to do the same thing and it needed a different method for SMTP but then I came across your template so now trying that out.

Thanks for the help.
