### ISSUE TITLE
Invalid discovery rule value: cannot parse as a valid JSON object:

### ISSUE THREAD

**Issue by HZO-IT** [ugoviti/zabbix-templates#11]
Invalid discovery rule value: cannot parse as a valid JSON object: invalid control character in string data at: 

![2021-08-09 15_54_56-Clipboard](https://user-images.githubusercontent.com/5092558/128768133-7e23273e-9fe2-4276-9798-dd5d6fa15d88.png)

**Comment by HZO-IT** [comment]
[url-monitor-csv.log](https://github.com/ugoviti/zabbix-templates/files/6957132/url-monitor-csv.log)

**Comment by ugoviti** [comment]
mmmm.... there is a strange character in the url line that can't be used, can you send me to ugo.viti(at)initzero.it the problematic url if not contain sensitive data? 

thank you

**Comment by yakhatape** [comment]
same issue here have you any idea to fix it ?

**Comment by ugoviti** [comment]
how many urls are you listed in the csv?

can you identify which url cause the truncation?

if the urls doesn't include sensitive datas can you send to me? ugo.viti(at)initzero.it

thank you

**Comment by yakhatape** [comment]
ok , the issue was between chair and keyboard. 
My collegue which deployed the CSV does it over windows RLF i've made a dos2unix on the csv on server side and now looks good.

**Comment by ugoviti** [comment]
ok thank you for the feedback, now I understand the issue...I'll sanitize the csv file with `dos2unix` before reading it.

already pushed in 60897cf32fe85a25818e738959aacf0167431481

Kind Regards
