### ISSUE TITLE
No Discovery

### ISSUE THREAD

**Issue by duanedtp** [ugoviti/zabbix-templates#12]
I've specified local csv with about 80 https URLs but nothing seems to be getting discovered.  This command "/etc/zabbix/scripts/url-monitor.sh url.discovery /etc/zabbix/sites.csv" works locally. I've set macros as well, still nothing in GUI

**Comment by ugoviti** [comment]
solved the problem by it self?

**Comment by duanedtp** [comment]
yea i went another route, using the system.run() in an item built into zabbix and curl the URLs and regex to filter required info.

**Comment by Hakim3i** [comment]
I had to install zabbix agent 2 and restart ubuntu for it to work on 6.2.
