### ISSUE TITLE
Add User-Agent into the Curl requests

### ISSUE THREAD

**Issue by yakhatape** [ugoviti/zabbix-templates#13]
Hi , 

We are facing on some website (which include some specific security behavior) a too many redirect due of the missing header User-Agent.

On my side i've added the following into the curl call : -H "User-Agent: Zabbix"

Best regards,

**Comment by yakhatape** [comment]
@ugoviti *

**Comment by ugoviti** [comment]
Hi, 

thank you for the useful tip! pushed an updated script with commit b82f34c50f0eb0b0d033c98699929ae2e25e11de

you can customize via variable too:

`curlUserAgent="Mozilla/5.0 (compatible; Zabbix-URL-Monitor/$version;)"`
