### ISSUE TITLE
pjsip peer reporting

### ISSUE THREAD

**Issue by timmrogers** [ugoviti/zabbix-templates#2]
I'm super impressed by your project, and it *almost* works for me. 

But I'd really like to get reporting and triggers on PJSIP peers which are available and unreachable - and that doesn't seem to be working. It is reporting on our PJSIP trunk - but not on the extensions.

Have I perhaps missed a step?

I've attached a screenshot of showing the reporting. 

Any help would be much appreciated. Thank you!

<img width="1508" alt="Screen Shot 2020-08-05 at 7 11 42 PM" src="https://user-images.githubusercontent.com/8450844/89483358-bb6c1680-d750-11ea-8289-d5574160a821.png">

**Comment by ugoviti** [comment]
Hi, thank you for you comment... 

I'm sorry, I missed your issue :)

with the latest release of the template I fixed these issues... Can you confirm so I can close this issue?

thank you!

**Comment by ugoviti** [comment]
fixed since April 2021 update
