### ISSUE TITLE
iax2 discovery returns error when not loaded

### ISSUE THREAD

**Issue by SimonHova** [ugoviti/zabbix-templates#4]
On some of our production systems, we don't load the iax2 modules. However, because the discovery code doesn't work properly, it keeps discovering a trunk named "no" and saying that it failed.

**Comment by ugoviti** [comment]
Hi,

thank you for your feedback... can you disable under "Discovery rules" of the template the "Discovery IAX2 Trunks" line?

You'll need to remove the discovered triggers for the hosts too.

Thankyou
