### ISSUE TITLE
Missing arguments on any value while checking Asterisk template

### ISSUE THREAD

**Issue by arjun-udaan** [ugoviti/zabbix-templates#7]
Hi I'm getting missing arguments... exiting when trying to test any items inside this template

ERROR: missing arguments... exiting
Zabbix 5.0, imported without dashboardards, yes i know its not compatable, wanted to know if this error is indeed related to version

Any idea on this?

**Comment by ugoviti** [comment]
Hi,

I'm exportet the template using Zabbix 5.2.x

What template are you talking about?

Kind regards

**Comment by arjun-udaan** [comment]
I'm talking about the asterisk template, sorry didn't mention that here

So on zabbix-templates/asterisk/zabbix_agentd.d/scripts/asterisk.sh

I can see that 

cmd="$1"shift
# exit on first errorset -e
[ -z "$cmd" ] &amp;&amp; echo "ERROR: missing arguments... exiting" &amp;&amp; exit 1

if $1 is empty exit and print ERROR: missing arguments... exiting

This is the same error what I'm getting when testing any items with in the template

**Comment by arjun-udaan** [comment]
Firstly thanks for responding and my bad coudn't add the code in format,
very new here, sorry for that

**Comment by ugoviti** [comment]
mmmm... the attached code is not correct, do you copy&paste the code or you downloaded via git clone?

can try to clone?

you can embed code here using "```" syntax, example:

```
this is a code block
```

Kind Regards

**Comment by arjun-udaan** [comment]
Hi Thanks for the tip, it worked it was indeed issued with how the sh file was copied to client-server,

Upon continuing with the test, I was able to get the item value for check.asterisk[service.status] as Up correctly, but all other items returned this error

"Unable to connect to remote asterisk (does /var/run/asterisk/asterisk.ctl exist?) "

I have already added all the lines mentioned in the readme file on the sudoers file, can you help me out on this?

**Comment by ugoviti** [comment]
Did you solve the problem?
