### ISSUE TITLE
Cannot tell sites with same name but different ports apart

### ISSUE THREAD

**Issue by Taomyn** [ugoviti/zabbix-templates#9]
I have two web services running on the same server i.e. same FQDN, but on different ports. Although the polling is separating them, the discovery does not for item/trigger names and the names shown in the graphs:

![image](https://user-images.githubusercontent.com/4365929/124006510-a9cfd500-d9da-11eb-8713-cff030e354e4.png)
![image](https://user-images.githubusercontent.com/4365929/124006125-2d3cf680-d9da-11eb-9318-60d911edef46.png)

Names have been obfuscated but they are the same.

This probably also affects the latency data, but I have disabled that part of the template as I am only interested in the SSL certificate dates.

**Comment by ugoviti** [comment]
Hi,

I'm aware of this behavior. 

a solution was to use the {#URL} macro instead the {#HOST} macro for the item name, but that make longer items name.

for example when monitoring urls like:

`https://www.amazon.it/gp/bestsellers/?ref_=nav_em_cs_bestsellers_0_1_1_2`

the items name become very long.

anyway I'm evaluating this change.. do you have many hosts to monitor with different ports and same hostname?

Kind regards

**Comment by ugoviti** [comment]
Hi,

just pushed b9487e0be834057e46163b8ff8dc18a791d1fbef 

can you update your url-monitor.sh script and import the new template in your zabbix server?

Let's me know if it's the expected result.

Thankyou 

Best Regards

**Comment by ugoviti** [comment]
forgot to rename triggers prototypes, please update your template using always the latest commit

**Comment by Taomyn** [comment]
Hi, I gave it a go but now I get when I run a discovery:

![image](https://user-images.githubusercontent.com/4365929/124307571-4e335200-db68-11eb-9e9b-c88c68b4e04c.png)

I also made the same changes to the template disabling all the latency items, but perhaps I made a mistake so I also attach an export of my copy for you to look at.

[zbx_export_templates.yaml.txt](https://github.com/ugoviti/zabbix-templates/files/6756027/zbx_export_templates.yaml.txt)

**Comment by ugoviti** [comment]
Strange, have you imported the new template version selecting all "Delete missing" check boxes?

can you try to:

- remote template to the host
- remove the template from templates
- import the template from scratch

Thank you

**Comment by Taomyn** [comment]
That's exactly what I did because I had customised the previous one, I removed it from all those places then imported the new one and made the same changes again to disable all the performance/latency checks.

**Comment by ugoviti** [comment]
Hi, 

I can't recreate your problem...
Just installed the url-monitor template in a new Zabbix 5.4.2 Server deploy and monitored 26 URLs:

```
$ cat /etc/zabbix/url-monitor.csv  | wc -l
26
```

And the discovery doesn't report issues...

do you have a new server installation to test url-monitor template from scratch?

Thank you

**Comment by Taomyn** [comment]
No I don't have another server at the moment, but did you try the template export of my version to see what happens?

**Comment by ugoviti** [comment]
Ok, I discovered your problem when importing your template version:

![image](https://user-images.githubusercontent.com/11528563/124470980-9b980500-dd9c-11eb-8aec-bdada032e298.png)

You should no delete or change anything from the original template, for example if you want change the {$URL_PATH_CSV} macro, you don't must change the template, ma only modify the macro inside your host configuration:

![image](https://user-images.githubusercontent.com/11528563/124471322-05b0aa00-dd9d-11eb-964e-8f2422e1dac7.png)

so you don't must delete items and triggers, but only disable after the discovery.

Kind Regards

**Comment by Taomyn** [comment]
Correcting the default value for the path to the CSV makes no difference, plus it worked before, and I have not deleted any items or triggers, if you actually look they are just disabled.

I always make the change at the template so that multiple uses are all changed at once otherwise maintenance/fixes are a nightmare.

**Comment by ugoviti** [comment]
closing... not any more a problem? reopen in case
